### ISSUE TITLE
File Manager: Sort by date issue

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#2057]
In FPP 8.2 and 8.3, sorting sequences by "Date Modified" does a string compare vs a Date compare.   As a result 12/31/2023 is before 11/11/2024

![image](https://github.com/user-attachments/assets/8f9f57fc-7529-47d0-bee1-cb88975321d8)

**Comment by OnlineDynamic** [comment]
fix added - please test to close issue

**Comment by ghormann** [comment]
@OnlineDynamic  I upgraded to the latest master and get javascript errors.

![Image](https://github.com/user-attachments/assets/37b64992-9053-4b86-8a8f-c3c304aab3ae)

**Comment by ghormann** [comment]
fpp-filemanager.js:1473 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://api.falconplayer.com https://raw.githubusercontent.com/FalconChristmas/fpp-data https://raw.githubusercontent.co".

    at SetupTableSorter (fpp-filemanager.js:1473:44)
    at Object.complete (fpp-filemanager.js:97:4)
    at c (jquery-latest.min.js…=1725207645:2:25304)
    at Object.fireWith (jquery-latest.min.js…=1725207645:2:26053)
    at l (jquery-latest.min.js…=1725207645:2:77910)
    at XMLHttpRequest.<anonymous> (jquery-latest.min.js…=1725207645:2:80265)

**Comment by ghormann** [comment]
Actually, I bet that is the apache change...   LEt me reboot.

**Comment by OnlineDynamic** [comment]
it is - if you run 

sudo /opt/fpp/scripts/ManageApacheContentPolicy.sh regenerate 

it should fix

**Comment by ghormann** [comment]
Looks good.  Closing.  Thanks @OnlineDynamic
