### ISSUE TITLE
PHP error viewing audio files in File Manager

### ISSUE THREAD

**Issue by sslupsky** [FalconChristmas/fpp#2070]
**FPP Version and Hardware**: 
FPP 8.3.1 running on BBE

**Describe the bug and Steps to reproduce**: 
When I selected the Audio tab in the File Manager to view the list of files an error is thrown and the list is empty.  I tracked the error down in the apache log and found a PHP error:
```
[Wed Nov 27 12:36:06.673488 2024] [proxy_fcgi:error] [pid 644:tid 714] [client 10.0.51.20:64903] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /opt/fpp/www/common.php:1435\nStack trace:\n#0 /opt/fpp/www/api/controllers/files.php(194): media_duration_cache()\n#1 /opt/fpp/www/api/controllers/files.php(244): GetFilesHelper()\n#2 /opt/fpp/www/api/lib/limonade.php(430): GetFiles()\n#3 /opt/fpp/www/api/index.php(189): run()\n#4 {main}\n  thrown in /opt/fpp/www/common.php on line 1435', referer: http://10.0.51.170/filemanager.php
```

I think this problem might be related to issue #1787.  As I recall, I restored my configuration from a backup and used FPP Connect in xLights to upload some sequences and media files.  After uploading the sequences when I checked that the sequences and media were uploaded using the File Manager and this is when I noticed the problem.  The sequences appear in the sequences tab but the audio tab is empty.  I ssh'ed into the instance and verified the audio files are in the media/music directory as expected.

![Screenshot 2024-11-27 at 1 05 57 PM](https://github.com/user-attachments/assets/45108171-1a15-4464-b1e2-4ab772107518)
[apache2-error.log](https://github.com/user-attachments/files/17939602/apache2-error.log)
![Screenshot 2024-11-27 at 1 07 21 PM](https://github.com/user-attachments/assets/014a3e2d-1b3b-47f3-b64a-d0e1ec4e7867)

**Comment by OnlineDynamic** [comment]
can you give the full list of music file names in music dir - thinking maybe a special character in a filename somewhere might be causing an issue - screen shot provided only goes to 'H' so guessing you have a load more files in there

**Comment by sslupsky** [comment]
Yeah, I check for weird characters but didn't find anything that looked suspicious.  Here is the list:

```
-rw-r--r--  1 fpp fpp  7355291 Nov 29 17:34 '04 Emmanuel.m4a'
-rw-r--r--  1 fpp fpp  7492390 Nov 29 17:33 '04 Wintersong.m4a'
-rw-r--r--  1 fpp fpp  4328424 Nov 29 17:27 'A Christmas Monologue - for king and country.m4a'
-rw-r--r--  1 fpp fpp  7811721 Nov 29 17:29 'Angels We Have Heard on High - The Piano Guys.m4a'
-rw-r--r--  1 fpp fpp  5821219 Nov 29 17:29 'Away in a Manger - Carrie Underwood.m4a'
-rw-r--r--  1 fpp fpp  7485123 Nov 29 17:29 'Believe - Adam Lambert.m4a'
-rw-r--r--  1 fpp fpp  7630326 Nov 29 17:28 'Believer - Imagine Dragons.m4a'
-rw-r--r--  1 fpp fpp  3069629 Nov 29 17:26 'Bluey - Theme Song Remix.mp3'
-rw-r--r--  1 fpp fpp  7995850 Nov 29 17:34 'Cantique de Noel - O Holy Night - whitney houston.m4a'
-rw-r--r--  1 fpp fpp  5972207 Nov 29 17:26 'Carol Of The Bells - David Foster.m4a'
-rw-r--r--  1 fpp fpp  8016117 Nov 29 17:30 'Christmas Cmon - Lindsey Stirling.m4a'
-rw-r--r--  1 fpp fpp  6039340 Nov 29 17:30 'Christmas Dream - Perry Como.m4a'
-rw-r--r--  1 fpp fpp  7972147 Nov 29 17:27 'Christmas  Every Day - Simple Plan.m4a'
-rw-r--r--  1 fpp fpp  7753103 Nov 29 17:35 'Christmas Just Aint Christmas - Idina Menzel.m4a'
-rw-r--r--  1 fpp fpp  8705828 Nov 29 17:26 'Christmas mix 2018.mp3'
-rw-r--r--  1 fpp fpp  7329520 Nov 29 17:31 'Christmas Sarajevo.mp3'
-rw-r--r--  1 fpp fpp  4068162 Nov 29 17:33 'Christmastime_Linus and Lucy.mp3'
-rw-r--r--  1 fpp fpp  4932693 Nov 29 17:31 'Colors of the Wind - torri kelly.mp3'
-rw-r--r--  1 fpp fpp  7680089 Nov 29 17:31 'Danger Zone - Kenny Loggins.m4a'
-rw-r--r--  1 fpp fpp  6519252 Dec  6 10:12 'Defying Gravity (Edited).mp3'
-rw-r--r--  1 fpp fpp  5969709 Nov 29 17:30 'Dominick the Donkey - Lou Monte.m4a'
-rw-r--r--  1 fpp fpp  6900779 Nov 29 17:28 'Dont Stop - Fleetwood Mac.m4a'
-rw-r--r--  1 fpp fpp  3968326 Dec  6 10:12 'Do You Hear What I Hear.mp3'
-rw-r--r--  1 fpp fpp   181315 Nov 29 17:27 'Electric Christmas Intro.mp3'
-rw-r--r--  1 fpp fpp  6226694 Nov 29 17:27 'Feels Like Joy - Micah Taylor.m4a'
-rw-r--r--  1 fpp fpp  1555364 Nov 29 17:29 'HAPPY NEW YEAR - 2024.m4a'
-rw-r--r--  1 fpp fpp  6579266 Nov 29 17:26 'Hark The Herald Angels Sing - Amy Grant.m4a'
-rw-r--r--  1 fpp fpp  1946500 Nov 29 17:33 'Holly Jolly Christmas.mp3'
-rw-r--r--  1 fpp fpp  5531688 Nov 29 17:31 'I Farted on Santas Lap.mp3'
-rw-r--r--  1 fpp fpp  8135835 Nov 29 17:34 'In Jesus Name (God Of Possible).m4a'
-rw-r--r--  1 fpp fpp  6677842 Nov 29 17:34 'Into the Unknown - Panic At The Disco.m4a'
-rw-r--r--  1 fpp fpp  7941869 Nov 29 17:26 'I See the Light - Mandy Moore.m4a'
-rw-r--r--  1 fpp fpp  7438465 Nov 29 17:33 'Its Beginning To Look a Lot Like Christmas- michael buble.m4a'
-rw-r--r--  1 fpp fpp  5716429 Nov 29 17:29 'I Want a Hippopotamus for Christmas - Gayla Peevy.m4a'
-rw-r--r--  1 fpp fpp  6352908 Nov 29 17:27 'Jingle Bells - Colton Dixon.m4a'
-rw-r--r--  1 fpp fpp  2575172 Nov 29 17:35 'Jingle Bells - Gwen Stefani - Short.mp3'
-rw-r--r--  1 fpp fpp  7527247 Nov 29 17:30 'Kid On Christmas - Pentatonix feat Meghan Trainor.m4a'
-rw-r--r--  1 fpp fpp  8229197 Nov 29 17:31 'Kiss Me Babe It is Christmas Time - Owl City.m4a'
-rw-r--r--  1 fpp fpp 46391668 Nov 29 17:34 'Last Christmas - Wham.wav'
-rw-r--r--  1 fpp fpp  3104341 Nov 29 17:28 'Let It Go - Frozen Broadway Musical.mp3'
-rw-r--r--  1 fpp fpp  8195373 Nov 29 17:32 'Let It Go - Idina Menzel.m4a'
-rw-r--r--  1 fpp fpp  8092853 Nov 29 17:31 'Light of Christmas - Owl City - toby mac.m4a'
-rw-r--r--  1 fpp fpp  9202256 Nov 29 17:34 'Light of the World - Lauren Daigle.m4a'
-rw-r--r--  1 fpp fpp  7208890 Nov 29 17:33 'Mary Did You Know - Pentatonix.m4a'
-rw-r--r--  1 fpp fpp  5170144 Nov 29 17:28 'Merry Christmas - Ed Sheeran and Elton John - synchronized.m4a'
-rw-r--r--  1 fpp fpp  6835355 Nov 29 17:30 'Merry Christmas To You - Sidewalk Prophets.m4a'
-rw-r--r--  1 fpp fpp  8096499 Nov 29 17:27 'My Jesus - Anne Wilson.m4a'
-rw-r--r--  1 fpp fpp  7440956 Nov 29 17:32 'Never Enough - loren allred.m4a'
-rw-r--r--  1 fpp fpp  9156478 Nov 29 17:29 'Noel - Chris Tomlin featuring Lauren Daigle.m4a'
-rw-r--r--  1 fpp fpp  9300331 Nov 29 17:32 'Noel - He Is Born - Tommee Profitt.m4a'
-rw-r--r--  1 fpp fpp  7269480 Nov 29 17:31 'O Come - Let Us Adore - Jordan Smith.m4a'
-rw-r--r--  1 fpp fpp  7066834 Nov 29 17:28 'O Come O Come Emmanuel - Tommee Profitt.m4a'
-rw-r--r--  1 fpp fpp  1793472 Nov 29 17:33 'O Holy Night - Celtic Women.mp3'
-rw-r--r--  1 fpp fpp  6633614 Nov 29 17:29 'Please Come Home for Christmas - The Eagles.m4a'
-rw-r--r--  1 fpp fpp  7336980 Nov 29 17:28 'River Flows In You.m4a'
-rw-r--r--  1 fpp fpp  8499733 Nov 29 17:27  River.m4a
-rw-r--r--  1 fpp fpp  5494988 Nov 29 17:29 'Rudolph the Red-Nosed Reindeer - Burl Ives.m4a'
-rw-r--r--  1 fpp fpp  4220010 Nov 29 17:33 'Santa Claus Is Coming to Town.m4a'
-rw-r--r--  1 fpp fpp  3015944 Nov 29 17:27 'Santa is Back in Town.mp3'
-rw-r--r--  1 fpp fpp  2525352 Nov 29 17:30 'Santa Shark Baby Shark Christmas Song Super Simple Songs.mp3'
-rw-r--r--  1 fpp fpp  7383069 Nov 29 17:29 'Shut Up and Dance - Walk The Moon.m4a'
-rw-r--r--  1 fpp fpp  7546926 Nov 29 17:28 'Silent Night - Riley Clemmons.m4a'
-rw-r--r--  1 fpp fpp  7407393 Nov 29 17:30 'Silent Night - The Piano Guys.m4a'
-rw-r--r--  1 fpp fpp  6624969 Dec  6 10:12 'Sleigh Ride - Johnny Mathis with Percy Faith.m4a'
-rw-r--r--  1 fpp fpp  6359115 Nov 29 17:28 'Small Town Christmas - Rob Thomas.m4a'
-rw-r--r--  1 fpp fpp  6793550 Nov 29 17:32 'Snow Waltz - Lindsey Stirling.m4a'
-rw-r--r--  1 fpp fpp  8267719 Nov 29 17:32 'Sounding Joy - Ellie Holcomb.m4a'
-rw-r--r--  1 fpp fpp  3498477 Nov 29 17:27 'Sponge Bob - Dont Be A Jerk Its Christmas.mp3'
-rw-r--r--  1 fpp fpp  7767501 Nov 29 17:27 'Taking Care of Christmas - Randy Bachman.m4a'
-rw-r--r--  1 fpp fpp  7521528 Nov 29 17:31 'The Christmas Song - Merry Christmas to You - Nat King Cole.m4a'
-rw-r--r--  1 fpp fpp   730309 Nov 29 17:27 'THX Intro.m4a'
-rw-r--r--  1 fpp fpp 11105574 Nov 29 17:28 'Twelve Days of Christmas.m4a'
-rw-r--r--  1 fpp fpp  8280611 Nov 29 17:33 'Underneath the Tree - Kelly Clarkson.m4a'
-rw-r--r--  1 fpp fpp  6470248 Nov 29 17:34 'Under the Christmas Lights - gwen stefani.m4a'
-rw-r--r--  1 fpp fpp 10826528 Nov 29 17:26 'What a Glorious Night - Sidewalk Prophets.m4a'
-rw-r--r--  1 fpp fpp  7734074 Nov 29 17:28 'What Child Is This.m4a'
-rw-r--r--  1 fpp fpp  9189068 Nov 29 17:26 'You are Here - Francesca Battistelli.m4a'
-rw-r--r--  1 fpp fpp  6016314 Nov 29 17:26 'You Make It Feel Like Christmas - w Blake Shelton - Gwen Stefani.m4a
```

**Comment by OnlineDynamic** [comment]
does the api call turn for you...?

http://192.168.0.100/api/media

**Comment by sslupsky** [comment]
It returns a list of the media.  I recall that I had to replace the controller.  Somehow FPP messed up the EEPROM and then the outputs were not configured as BBB16 outputs anymore ... something "serial" but I don't recall exactly.  I will have to go dig up that controller and get that info.  It is a separate issue for sure but it caused me to replace it.  I tried re-imaging the SD card and refreshing the EEPROM using FPP and it still caused the same issue ... incorrect output configuration.  Cannot be sure the issue was related to doing the upgrade but I am suspicious that was the cause.

**Comment by ghormann** [comment]
I tried uploading mp3 files to my dev box running "current"  and then clicking the "Listen" button.   I was not able to reproduce.   Would have to see the full json file in the output to review further.

**Comment by sslupsky** [comment]
@ghormann I do not recall the issue was related to the listen function.  Just listing the music directory was throwing the error.  I ended up replacing the Sancloud Beaglebone Enhanced because I was experiencing a hard crash.  Tried two different Sancloud BBE's and had similar problems.

**Comment by sslupsky** [comment]
Here is a copy of the error log.

[apache2-error.log](https://github.com/user-attachments/files/18270308/apache2-error.log)

**Comment by sslupsky** [comment]
Here is a copy of the syslog as well.  Not much to see here around the time the php error was thrown.
[syslog.zip](https://github.com/user-attachments/files/18270335/syslog.zip)

**Comment by ghormann** [comment]
@sslupsky  So how do I reproduce the problem?  Just go to the Audio tab?  If so, then we need the exact output (copy and paste) from http://192.168.0.100/api/media

**Comment by darylc** [comment]
@sslupsky ?

**Comment by sslupsky** [comment]
@darylc. I've encountered the issue three or four times but never been able to identify a method to reproduce it reliably.  As mentioned earlier the problem appears related to the upgrade process.  When I re-image the SD card I have not encountered the issue.

I'll close the issue and reopen if I determine what is causing this.
